### ISSUE TITLE
RuntimeError: Caught RuntimeError in DataLoader worker process 2. RuntimeError: result type Float can't be cast to the desired output type Long

### ISSUE THREAD

**Issue by EMB310HH** [SvipRepetitionCounting/TransRAC#17]
Hello contributors, I made the following errors when implementing your code. Can you give me some suggestions? I will be grateful!

**Comment by EMB310HH** [comment]
When the training reaches 10 epoch, the following errors occur:
Traceback (most recent call last):███████████████████████████████████████████████▎                                             | 30/48 [02:20<01:24,  4.69s/it, Epoch=10, loss_train=0.0525, Train MAE=0.29, Train OBO =0.312]
  File "train.py", line 48, in <module>
    lastckpt=lastckpt, mae_error=False)
  File "/home/ai/TransRAC-main/training/train_looping.py", line 70, in train_loop
    for input, target in pbar:
File "/home/ai/anaconda3/envs/trans/lib/python3.7/site-packages/tqdm/_tqdm.py", line 897, in __iter__
    for obj in iterable:
  File "/home/ai/anaconda3/envs/trans/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/ai/anaconda3/envs/trans/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/home/ai/anaconda3/envs/trans/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/ai/anaconda3/envs/trans/lib/python3.7/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "/home/ai/anaconda3/envs/trans/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ai/anaconda3/envs/trans/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/ai/anaconda3/envs/trans/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 83, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/home/ai/anaconda3/envs/trans/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 83, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/home/ai/anaconda3/envs/trans/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: result type Float can't be cast to the desired output type Long

**Comment by 957001934** [comment]
The error is too unexpected, and we never encountered it. Maybe you can try to restart it.
